id: PE8E41E91
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4867
  instance_id: http://purl.bdrc.io/resource/IE1KG4867
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རྩིས་རིག་ཤེས་བྱ་ཀུན་གསལ།
  alt_title:
    en:
    - 'fortunate astrological knowledge drawer : the vision of all wisdom'
  author: http://purl.bdrc.io/resource/P1CZ2379
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    534a112f522448d19d3b85eee9125119:
      title: པོད ༡་རྩིས་རིག་ཤེས་བྱ་ཀུན་གསལ
      volume_number: 1
      base_file: UT1KG4867_I1KG5031_0000.txt
      reference: http://purl.bdrc.io/resource/VL3D3BDA4695E0B59D
      image_group: I1KG5031
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG4867
  - http://purl.bdrc.io/resource/W1KG4867
  ocr_software: Namsel
created_at: '2021-12-22T10:44:47.863468'
last_modified_at: '2021-12-22T10:44:47.863475'
statistics:
  total_words: 58167
  total_non_words: 12352
quality:
  non_words_ratio: 0.21
